// Stick figure pose data for each tennis stroke phase
// Each pose defines joint positions as {x, y} normalized to a 100x160 canvas
// Joints: head, neck, shoulderL, shoulderR, elbowL, elbowR, wristL, wristR,
//         hip, kneeL, kneeR, ankleL, ankleR
// Racket tip position included for wrist-side hand

export const strokes = [
  {
    id: "forehand",
    name: "Forehand",
    description: "The most common attacking shot, hit with the dominant hand sweeping across the body.",
    tips: [
      "Turn sideways early — rotate hips and shoulders",
      "Keep your eye on the ball through contact",
      "Swing low-to-high for topspin",
      "Follow through over your opposite shoulder",
    ],
    phases: [
      {
        label: "Ready Position",
        cue: "Feet shoulder-width apart, knees bent, racket in front.",
        pose: {
          head:      { x: 50, y: 10 },
          neck:      { x: 50, y: 20 },
          shoulderL: { x: 38, y: 28 },
          shoulderR: { x: 62, y: 28 },
          elbowL:    { x: 34, y: 42 },
          elbowR:    { x: 66, y: 42 },
          wristL:    { x: 44, y: 52 },
          wristR:    { x: 56, y: 52 },
          hip:       { x: 50, y: 62 },
          kneeL:     { x: 40, y: 85 },
          kneeR:     { x: 60, y: 85 },
          ankleL:    { x: 36, y: 110 },
          ankleR:    { x: 64, y: 110 },
          racketTip: { x: 50, y: 35 },
          racketHand: "both",
        },
      },
      {
        label: "Backswing",
        cue: "Rotate right shoulder back, take racket back low.",
        pose: {
          head:      { x: 50, y: 10 },
          neck:      { x: 50, y: 20 },
          shoulderL: { x: 42, y: 27 },
          shoulderR: { x: 68, y: 30 },
          elbowL:    { x: 40, y: 40 },
          elbowR:    { x: 78, y: 46 },
          wristL:    { x: 44, y: 52 },
          wristR:    { x: 84, y: 62 },
          hip:       { x: 50, y: 62 },
          kneeL:     { x: 38, y: 85 },
          kneeR:     { x: 62, y: 85 },
          ankleL:    { x: 32, y: 110 },
          ankleR:    { x: 66, y: 110 },
          racketTip: { x: 92, y: 80 },
          racketHand: "right",
        },
      },
      {
        label: "Forward Swing",
        cue: "Drive hips forward, swing the racket low-to-high.",
        pose: {
          head:      { x: 50, y: 10 },
          neck:      { x: 50, y: 20 },
          shoulderL: { x: 36, y: 28 },
          shoulderR: { x: 60, y: 28 },
          elbowL:    { x: 30, y: 42 },
          elbowR:    { x: 68, y: 38 },
          wristL:    { x: 34, y: 54 },
          wristR:    { x: 74, y: 48 },
          hip:       { x: 50, y: 62 },
          kneeL:     { x: 38, y: 85 },
          kneeR:     { x: 62, y: 83 },
          ankleL:    { x: 34, y: 110 },
          ankleR:    { x: 64, y: 110 },
          racketTip: { x: 82, y: 32 },
          racketHand: "right",
        },
      },
      {
        label: "Contact",
        cue: "Strike the ball out in front, arm extended, strings flat.",
        pose: {
          head:      { x: 48, y: 10 },
          neck:      { x: 48, y: 20 },
          shoulderL: { x: 34, y: 27 },
          shoulderR: { x: 58, y: 27 },
          elbowL:    { x: 28, y: 40 },
          elbowR:    { x: 72, y: 36 },
          wristL:    { x: 32, y: 52 },
          wristR:    { x: 84, y: 38 },
          hip:       { x: 48, y: 62 },
          kneeL:     { x: 36, y: 84 },
          kneeR:     { x: 60, y: 82 },
          ankleL:    { x: 30, y: 110 },
          ankleR:    { x: 62, y: 110 },
          racketTip: { x: 98, y: 28 },
          racketHand: "right",
        },
      },
      {
        label: "Follow Through",
        cue: "Racket finishes over the left shoulder, body rotates fully.",
        pose: {
          head:      { x: 46, y: 10 },
          neck:      { x: 46, y: 20 },
          shoulderL: { x: 30, y: 28 },
          shoulderR: { x: 56, y: 26 },
          elbowL:    { x: 28, y: 22 },
          elbowR:    { x: 56, y: 28 },
          wristL:    { x: 36, y: 14 },
          wristR:    { x: 54, y: 20 },
          hip:       { x: 46, y: 62 },
          kneeL:     { x: 34, y: 84 },
          kneeR:     { x: 58, y: 82 },
          ankleL:    { x: 28, y: 110 },
          ankleR:    { x: 60, y: 110 },
          racketTip: { x: 22, y: 8 },
          racketHand: "right",
        },
      },
    ],
  },
  {
    id: "backhand",
    name: "Two-Handed Backhand",
    description: "A powerful shot hit across the body using both hands for stability and control.",
    tips: [
      "Rotate shoulders early — coil like a spring",
      "Both hands on the racket through contact",
      "Contact point slightly in front of the hip",
      "High finish brings the ball up with topspin",
    ],
    phases: [
      {
        label: "Ready Position",
        cue: "Same neutral ready stance as the forehand.",
        pose: {
          head:      { x: 50, y: 10 },
          neck:      { x: 50, y: 20 },
          shoulderL: { x: 38, y: 28 },
          shoulderR: { x: 62, y: 28 },
          elbowL:    { x: 34, y: 42 },
          elbowR:    { x: 66, y: 42 },
          wristL:    { x: 44, y: 52 },
          wristR:    { x: 56, y: 52 },
          hip:       { x: 50, y: 62 },
          kneeL:     { x: 40, y: 85 },
          kneeR:     { x: 60, y: 85 },
          ankleL:    { x: 36, y: 110 },
          ankleR:    { x: 64, y: 110 },
          racketTip: { x: 50, y: 35 },
          racketHand: "both",
        },
      },
      {
        label: "Backswing",
        cue: "Rotate left shoulder back, both hands take racket left.",
        pose: {
          head:      { x: 50, y: 10 },
          neck:      { x: 50, y: 20 },
          shoulderL: { x: 30, y: 28 },
          shoulderR: { x: 56, y: 26 },
          elbowL:    { x: 22, y: 42 },
          elbowR:    { x: 42, y: 42 },
          wristL:    { x: 16, y: 54 },
          wristR:    { x: 26, y: 54 },
          hip:       { x: 50, y: 62 },
          kneeL:     { x: 38, y: 85 },
          kneeR:     { x: 62, y: 85 },
          ankleL:    { x: 34, y: 110 },
          ankleR:    { x: 66, y: 110 },
          racketTip: { x: 8, y: 72 },
          racketHand: "left",
        },
      },
      {
        label: "Forward Swing",
        cue: "Uncoil hips, drive the racket through low-to-high.",
        pose: {
          head:      { x: 50, y: 10 },
          neck:      { x: 50, y: 20 },
          shoulderL: { x: 34, y: 28 },
          shoulderR: { x: 62, y: 28 },
          elbowL:    { x: 30, y: 40 },
          elbowR:    { x: 64, y: 40 },
          wristL:    { x: 38, y: 50 },
          wristR:    { x: 56, y: 50 },
          hip:       { x: 50, y: 62 },
          kneeL:     { x: 38, y: 84 },
          kneeR:     { x: 62, y: 84 },
          ankleL:    { x: 34, y: 110 },
          ankleR:    { x: 64, y: 110 },
          racketTip: { x: 28, y: 34 },
          racketHand: "left",
        },
      },
      {
        label: "Contact",
        cue: "Both arms extended, racket face perpendicular to the ball.",
        pose: {
          head:      { x: 50, y: 10 },
          neck:      { x: 50, y: 20 },
          shoulderL: { x: 32, y: 26 },
          shoulderR: { x: 62, y: 30 },
          elbowL:    { x: 16, y: 36 },
          elbowR:    { x: 42, y: 44 },
          wristL:    { x: 6,  y: 38 },
          wristR:    { x: 22, y: 46 },
          hip:       { x: 50, y: 62 },
          kneeL:     { x: 36, y: 84 },
          kneeR:     { x: 62, y: 82 },
          ankleL:    { x: 30, y: 110 },
          ankleR:    { x: 64, y: 110 },
          racketTip: { x: 2,  y: 24 },
          racketHand: "left",
        },
      },
      {
        label: "Follow Through",
        cue: "Racket finishes high on the right side, chest faces net.",
        pose: {
          head:      { x: 50, y: 10 },
          neck:      { x: 50, y: 20 },
          shoulderL: { x: 36, y: 26 },
          shoulderR: { x: 66, y: 28 },
          elbowL:    { x: 52, y: 16 },
          elbowR:    { x: 72, y: 34 },
          wristL:    { x: 62, y: 8 },
          wristR:    { x: 74, y: 24 },
          hip:       { x: 50, y: 62 },
          kneeL:     { x: 36, y: 84 },
          kneeR:     { x: 62, y: 82 },
          ankleL:    { x: 30, y: 110 },
          ankleR:    { x: 64, y: 110 },
          racketTip: { x: 68, y: 2 },
          racketHand: "left",
        },
      },
    ],
  },
  {
    id: "serve",
    name: "Serve",
    description: "The shot that starts every point — a full-body motion from toss to powerful strike.",
    tips: [
      "Toss the ball slightly in front and to the right",
      "Bend your knees in the trophy pose",
      "Explode upward and pronate the forearm at contact",
      "Land inside the baseline on the follow-through",
    ],
    phases: [
      {
        label: "Stance",
        cue: "Stand sideways to baseline, feet staggered, relaxed grip.",
        pose: {
          head:      { x: 50, y: 10 },
          neck:      { x: 50, y: 20 },
          shoulderL: { x: 36, y: 28 },
          shoulderR: { x: 60, y: 28 },
          elbowL:    { x: 32, y: 44 },
          elbowR:    { x: 62, y: 44 },
          wristL:    { x: 32, y: 58 },
          wristR:    { x: 60, y: 58 },
          hip:       { x: 50, y: 65 },
          kneeL:     { x: 40, y: 87 },
          kneeR:     { x: 60, y: 87 },
          ankleL:    { x: 36, y: 112 },
          ankleR:    { x: 62, y: 112 },
          racketTip: { x: 62, y: 44 },
          racketHand: "right",
        },
      },
      {
        label: "Toss & Backswing",
        cue: "Left arm lifts the ball; right arm swings down and back.",
        pose: {
          head:      { x: 48, y: 8 },
          neck:      { x: 48, y: 18 },
          shoulderL: { x: 34, y: 26 },
          shoulderR: { x: 60, y: 28 },
          elbowL:    { x: 28, y: 16 },
          elbowR:    { x: 68, y: 44 },
          wristL:    { x: 24, y: 6 },
          wristR:    { x: 74, y: 58 },
          hip:       { x: 50, y: 65 },
          kneeL:     { x: 40, y: 87 },
          kneeR:     { x: 60, y: 87 },
          ankleL:    { x: 36, y: 112 },
          ankleR:    { x: 62, y: 112 },
          racketTip: { x: 82, y: 72 },
          racketHand: "right",
        },
      },
      {
        label: "Trophy Pose",
        cue: "Knees bent, racket behind head, left arm still pointing up.",
        pose: {
          head:      { x: 48, y: 10 },
          neck:      { x: 48, y: 20 },
          shoulderL: { x: 34, y: 26 },
          shoulderR: { x: 60, y: 26 },
          elbowL:    { x: 26, y: 16 },
          elbowR:    { x: 66, y: 16 },
          wristL:    { x: 20, y: 6 },
          wristR:    { x: 68, y: 8 },
          hip:       { x: 50, y: 68 },
          kneeL:     { x: 38, y: 90 },
          kneeR:     { x: 60, y: 90 },
          ankleL:    { x: 34, y: 112 },
          ankleR:    { x: 62, y: 112 },
          racketTip: { x: 74, y: 24 },
          racketHand: "right",
        },
      },
      {
        label: "Contact",
        cue: "Fully extended, arm straight up, at maximum height.",
        pose: {
          head:      { x: 48, y: 8 },
          neck:      { x: 48, y: 18 },
          shoulderL: { x: 36, y: 24 },
          shoulderR: { x: 60, y: 22 },
          elbowL:    { x: 30, y: 36 },
          elbowR:    { x: 68, y: 10 },
          wristL:    { x: 32, y: 48 },
          wristR:    { x: 72, y: 2 },
          hip:       { x: 50, y: 65 },
          kneeL:     { x: 40, y: 86 },
          kneeR:     { x: 60, y: 86 },
          ankleL:    { x: 36, y: 112 },
          ankleR:    { x: 62, y: 112 },
          racketTip: { x: 76, y: -10 },
          racketHand: "right",
        },
      },
      {
        label: "Follow Through",
        cue: "Arm swings across body, land with left foot forward.",
        pose: {
          head:      { x: 50, y: 12 },
          neck:      { x: 50, y: 22 },
          shoulderL: { x: 38, y: 28 },
          shoulderR: { x: 62, y: 26 },
          elbowL:    { x: 34, y: 42 },
          elbowR:    { x: 56, y: 38 },
          wristL:    { x: 36, y: 54 },
          wristR:    { x: 42, y: 56 },
          hip:       { x: 50, y: 65 },
          kneeL:     { x: 38, y: 84 },
          kneeR:     { x: 60, y: 88 },
          ankleL:    { x: 42, y: 110 },
          ankleR:    { x: 62, y: 114 },
          racketTip: { x: 26, y: 68 },
          racketHand: "right",
        },
      },
    ],
  },
  {
    id: "volley",
    name: "Forehand Volley",
    description: "A punch shot hit near the net before the ball bounces — compact and decisive.",
    tips: [
      "Minimal backswing — punch, don't swing",
      "Step into the ball with the opposite foot",
      "Keep the racket face open (slightly tilted back)",
      "Firm wrist through contact",
    ],
    phases: [
      {
        label: "Ready Position",
        cue: "Closer to the net, weight forward, racket up.",
        pose: {
          head:      { x: 50, y: 10 },
          neck:      { x: 50, y: 20 },
          shoulderL: { x: 38, y: 27 },
          shoulderR: { x: 62, y: 27 },
          elbowL:    { x: 34, y: 38 },
          elbowR:    { x: 66, y: 38 },
          wristL:    { x: 42, y: 48 },
          wristR:    { x: 58, y: 48 },
          hip:       { x: 50, y: 60 },
          kneeL:     { x: 40, y: 82 },
          kneeR:     { x: 60, y: 82 },
          ankleL:    { x: 36, y: 108 },
          ankleR:    { x: 64, y: 108 },
          racketTip: { x: 50, y: 30 },
          racketHand: "both",
        },
      },
      {
        label: "Short Backswing",
        cue: "Turn the shoulder slightly — racket goes back only to shoulder level.",
        pose: {
          head:      { x: 50, y: 10 },
          neck:      { x: 50, y: 20 },
          shoulderL: { x: 40, y: 27 },
          shoulderR: { x: 64, y: 28 },
          elbowL:    { x: 36, y: 38 },
          elbowR:    { x: 72, y: 38 },
          wristL:    { x: 42, y: 48 },
          wristR:    { x: 78, y: 44 },
          hip:       { x: 50, y: 60 },
          kneeL:     { x: 40, y: 82 },
          kneeR:     { x: 60, y: 82 },
          ankleL:    { x: 36, y: 108 },
          ankleR:    { x: 64, y: 108 },
          racketTip: { x: 86, y: 32 },
          racketHand: "right",
        },
      },
      {
        label: "Contact",
        cue: "Step forward with left foot, punch through the ball.",
        pose: {
          head:      { x: 48, y: 10 },
          neck:      { x: 48, y: 20 },
          shoulderL: { x: 34, y: 26 },
          shoulderR: { x: 60, y: 27 },
          elbowL:    { x: 28, y: 38 },
          elbowR:    { x: 70, y: 34 },
          wristL:    { x: 30, y: 48 },
          wristR:    { x: 82, y: 36 },
          hip:       { x: 48, y: 60 },
          kneeL:     { x: 36, y: 80 },
          kneeR:     { x: 60, y: 82 },
          ankleL:    { x: 28, y: 106 },
          ankleR:    { x: 62, y: 108 },
          racketTip: { x: 96, y: 26 },
          racketHand: "right",
        },
      },
      {
        label: "Follow Through",
        cue: "Short finish — racket stops in front, don't over-swing.",
        pose: {
          head:      { x: 48, y: 10 },
          neck:      { x: 48, y: 20 },
          shoulderL: { x: 34, y: 26 },
          shoulderR: { x: 60, y: 26 },
          elbowL:    { x: 28, y: 38 },
          elbowR:    { x: 68, y: 32 },
          wristL:    { x: 30, y: 48 },
          wristR:    { x: 76, y: 28 },
          hip:       { x: 48, y: 60 },
          kneeL:     { x: 36, y: 80 },
          kneeR:     { x: 60, y: 82 },
          ankleL:    { x: 28, y: 106 },
          ankleR:    { x: 62, y: 108 },
          racketTip: { x: 88, y: 18 },
          racketHand: "right",
        },
      },
    ],
  },
  {
    id: "smash",
    name: "Overhead Smash",
    description: "An aggressive overhead shot used to finish the point when the opponent lobs.",
    tips: [
      "Move quickly to get under the ball",
      "Point at the ball with non-dominant hand",
      "Trophy pose — same as the serve",
      "Snap the wrist and hit out in front",
    ],
    phases: [
      {
        label: "Positioning",
        cue: "Move back fast, turn sideways, point left hand at the ball.",
        pose: {
          head:      { x: 48, y: 8 },
          neck:      { x: 48, y: 18 },
          shoulderL: { x: 34, y: 26 },
          shoulderR: { x: 60, y: 28 },
          elbowL:    { x: 24, y: 16 },
          elbowR:    { x: 64, y: 42 },
          wristL:    { x: 16, y: 6 },
          wristR:    { x: 68, y: 52 },
          hip:       { x: 50, y: 62 },
          kneeL:     { x: 40, y: 84 },
          kneeR:     { x: 60, y: 84 },
          ankleL:    { x: 36, y: 110 },
          ankleR:    { x: 62, y: 110 },
          racketTip: { x: 78, y: 66 },
          racketHand: "right",
        },
      },
      {
        label: "Trophy Pose",
        cue: "Racket up behind head, weight loaded, knees slightly bent.",
        pose: {
          head:      { x: 48, y: 10 },
          neck:      { x: 48, y: 20 },
          shoulderL: { x: 34, y: 26 },
          shoulderR: { x: 60, y: 26 },
          elbowL:    { x: 26, y: 16 },
          elbowR:    { x: 66, y: 14 },
          wristL:    { x: 20, y: 6 },
          wristR:    { x: 68, y: 6 },
          hip:       { x: 50, y: 64 },
          kneeL:     { x: 40, y: 86 },
          kneeR:     { x: 60, y: 88 },
          ankleL:    { x: 36, y: 112 },
          ankleR:    { x: 62, y: 112 },
          racketTip: { x: 72, y: 22 },
          racketHand: "right",
        },
      },
      {
        label: "Contact",
        cue: "Fully extended arm, hit slightly out front above the head.",
        pose: {
          head:      { x: 48, y: 8 },
          neck:      { x: 48, y: 18 },
          shoulderL: { x: 34, y: 24 },
          shoulderR: { x: 60, y: 22 },
          elbowL:    { x: 28, y: 34 },
          elbowR:    { x: 68, y: 8 },
          wristL:    { x: 32, y: 46 },
          wristR:    { x: 72, y: 0 },
          hip:       { x: 50, y: 62 },
          kneeL:     { x: 40, y: 84 },
          kneeR:     { x: 60, y: 84 },
          ankleL:    { x: 36, y: 110 },
          ankleR:    { x: 62, y: 110 },
          racketTip: { x: 76, y: -12 },
          racketHand: "right",
        },
      },
      {
        label: "Follow Through",
        cue: "Arm swings down across the body, recover to ready position.",
        pose: {
          head:      { x: 50, y: 12 },
          neck:      { x: 50, y: 22 },
          shoulderL: { x: 38, y: 28 },
          shoulderR: { x: 62, y: 26 },
          elbowL:    { x: 34, y: 40 },
          elbowR:    { x: 54, y: 36 },
          wristL:    { x: 36, y: 52 },
          wristR:    { x: 44, y: 52 },
          hip:       { x: 50, y: 64 },
          kneeL:     { x: 38, y: 84 },
          kneeR:     { x: 60, y: 86 },
          ankleL:    { x: 36, y: 110 },
          ankleR:    { x: 62, y: 112 },
          racketTip: { x: 30, y: 66 },
          racketHand: "right",
        },
      },
    ],
  },
];
